import type { Appointment } from '@/types';

export const appointments: Appointment[] = [
  {
    id: 'appt-sara-1',
    patientId: 'p-citizen-1',
    title: 'ویزیت پیگیری فشار خون',
    description: 'بررسی فشار خون و تنظیم دوز لوزارتان',
    providerId: 'p-careteam-1',
    providerName: 'دکتر علی رضایی',
    specialty: 'پزشک عمومی / داخلی',
    centerId: 'center-clinic-1',
    centerName: 'کلینیک سلامت ولیعصر',
    mode: 'in_person',
    scheduledAt: '2025-07-25T09:00:00.000Z',
    durationMinutes: 30,
    status: 'scheduled',
    location: 'طبقه ۲، اتاق ۲۰۵',
    reminderSent: true,
    sourceType: 'care_team',
    verificationStatus: 'verified',
    createdAt: '2025-07-01T10:00:00.000Z',
    updatedAt: '2025-07-15T08:00:00.000Z',
  },
  {
    id: 'appt-sara-2',
    patientId: 'p-citizen-1',
    title: 'مشاوره تغذیه',
    description: 'برنامه غذایی برای کنترل LDL',
    providerName: 'مهسا رحمانی',
    specialty: 'متخصص تغذیه',
    centerId: 'center-clinic-2',
    centerName: 'مرکز تغذیه سالم',
    mode: 'video',
    scheduledAt: '2025-08-05T14:00:00.000Z',
    durationMinutes: 45,
    status: 'scheduled',
    sourceType: 'user_entered',
    verificationStatus: 'self_reported',
    createdAt: '2025-07-10T11:00:00.000Z',
    updatedAt: '2025-07-10T11:00:00.000Z',
  },
  {
    id: 'appt-sara-3',
    patientId: 'p-citizen-1',
    title: 'معاینه دندانپزشکی',
    providerName: 'دکتر سارا نیک‌پور',
    specialty: 'دندانپزشکی',
    centerId: 'center-dental-1',
    centerName: 'کلینیک دندانپزشکی نیک',
    mode: 'in_person',
    scheduledAt: '2025-07-15T10:30:00.000Z',
    durationMinutes: 60,
    status: 'completed',
    location: 'واحد ۳',
    sourceType: 'user_entered',
    verificationStatus: 'verified',
    createdAt: '2025-06-01T08:00:00.000Z',
    updatedAt: '2025-07-15T11:30:00.000Z',
  },
  {
    id: 'appt-sara-4',
    patientId: 'p-citizen-1',
    title: 'آزمایش خون پیگیری',
    providerId: 'p-careteam-1',
    providerName: 'دکتر علی رضایی',
    specialty: 'پزشک عمومی',
    centerId: 'center-lab-1',
    centerName: 'آزمایشگاه پاتوبیولوژی پارس',
    mode: 'in_person',
    scheduledAt: '2025-04-10T07:00:00.000Z',
    durationMinutes: 15,
    status: 'completed',
    notes: 'ناشتا — TSH، لیپید پروفایل',
    sourceType: 'care_team',
    verificationStatus: 'verified',
    createdAt: '2025-03-20T09:00:00.000Z',
    updatedAt: '2025-04-10T08:00:00.000Z',
  },
  {
    id: 'appt-mother-1',
    patientId: 'p-mother-1',
    title: 'ویزیت دیابت',
    description: 'بررسی HbA1c و تنظیم دارو',
    providerId: 'p-careteam-1',
    providerName: 'دکتر علی رضایی',
    specialty: 'غدد و متابولیسم',
    centerId: 'center-hospital-1',
    centerName: 'بیمارستان امام خمینی',
    mode: 'in_person',
    scheduledAt: '2025-08-10T08:30:00.000Z',
    durationMinutes: 30,
    status: 'scheduled',
    location: 'کلینیک دیابت، طبقه ۱',
    sourceType: 'care_team',
    verificationStatus: 'verified',
    createdAt: '2025-05-02T10:00:00.000Z',
    updatedAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'appt-mother-2',
    patientId: 'p-mother-1',
    title: 'فیزیوتراپی زانو',
    providerName: 'مهدی صادقی',
    specialty: 'فیزیوتراپی',
    centerId: 'center-rehab-1',
    centerName: 'مرکز توانبخشی آرام',
    mode: 'in_person',
    scheduledAt: '2025-07-22T10:00:00.000Z',
    durationMinutes: 45,
    status: 'scheduled',
    sourceType: 'care_team',
    verificationStatus: 'verified',
    createdAt: '2025-06-15T08:00:00.000Z',
    updatedAt: '2025-06-15T08:00:00.000Z',
  },
  {
    id: 'appt-child-1',
    patientId: 'p-child-1',
    title: 'ویزیت اطفال — پیگیری آسم',
    providerName: 'دکتر زهرا موسوی',
    specialty: 'اطفال',
    centerId: 'center-clinic-3',
    centerName: 'کلینیک کودکان مهر',
    mode: 'in_person',
    scheduledAt: '2025-08-01T11:00:00.000Z',
    durationMinutes: 30,
    status: 'scheduled',
    sourceType: 'care_team',
    verificationStatus: 'verified',
    createdAt: '2025-07-01T09:00:00.000Z',
    updatedAt: '2025-07-01T09:00:00.000Z',
  },
  {
    id: 'appt-child-2',
    patientId: 'p-child-1',
    title: 'واکسن آنفولانزا',
    providerName: 'مرکز بهداشت منطقه ۳',
    specialty: 'واکسیناسیون',
    centerId: 'center-clinic-4',
    centerName: 'مرکز بهداشت منطقه ۳',
    mode: 'in_person',
    scheduledAt: '2025-10-01T09:00:00.000Z',
    durationMinutes: 15,
    status: 'scheduled',
    sourceType: 'integrated_system',
    verificationStatus: 'verified',
    createdAt: '2025-06-01T08:00:00.000Z',
    updatedAt: '2025-06-01T08:00:00.000Z',
  },
  {
    id: 'appt-spouse-1',
    patientId: 'p-spouse-1',
    title: 'معاینه سالانه',
    providerName: 'دکتر علی رضایی',
    specialty: 'پزشک عمومی',
    centerId: 'center-clinic-1',
    centerName: 'کلینیک سلامت ولیعصر',
    mode: 'in_person',
    scheduledAt: '2025-09-15T16:00:00.000Z',
    durationMinutes: 30,
    status: 'scheduled',
    sourceType: 'user_entered',
    verificationStatus: 'self_reported',
    createdAt: '2025-07-05T10:00:00.000Z',
    updatedAt: '2025-07-05T10:00:00.000Z',
  },
  {
    id: 'appt-sara-5',
    patientId: 'p-citizen-1',
    title: 'مشاوره روانشناسی (لغو شده)',
    providerName: 'دکتر نیلوفر باقری',
    specialty: 'روانشناسی بالینی',
    centerId: 'center-mental-1',
    centerName: 'مرکز سلامت روان آوا',
    mode: 'video',
    scheduledAt: '2025-06-20T15:00:00.000Z',
    durationMinutes: 50,
    status: 'cancelled',
    notes: 'لغو توسط بیمار',
    sourceType: 'user_entered',
    verificationStatus: 'self_reported',
    createdAt: '2025-06-01T08:00:00.000Z',
    updatedAt: '2025-06-18T12:00:00.000Z',
  },
];

export const appointmentsByPatient = (patientId: string): Appointment[] =>
  appointments.filter((a) => a.patientId === patientId);

export const upcomingAppointments = appointments
  .filter((a) => a.status === 'scheduled' && new Date(a.scheduledAt) > new Date())
  .sort((a, b) => new Date(a.scheduledAt).getTime() - new Date(b.scheduledAt).getTime());
