import type { Screening, ScreeningResult } from '@/types';

// ─── Questionnaire Definitions ──────────────────────────────────────────────────

export const screenings: Screening[] = [
  {
    id: 'screening-bmi',
    slug: 'bmi',
    category: 'bmi',
    title: 'محاسبه BMI و ارزیابی وزن',
    description: 'با وارد کردن قد و وزن، شاخص توده بدنی (BMI) شما محاسبه و تفسیر می‌شود.',
    estimatedMinutes: 2,
    isActive: true,
    targetAudience: 'همه بزرگسالان',
    disclaimer: 'این ابزار جایگزین معاینه پزشکی نیست.',
    questions: [
      {
        id: 'bmi-height',
        text: 'قد شما (سانتی‌متر)',
        type: 'number',
        required: true,
        min: 100,
        max: 250,
        unit: 'cm',
        helpText: 'مثال: ۱۶۵',
      },
      {
        id: 'bmi-weight',
        text: 'وزن شما (کیلوگرم)',
        type: 'number',
        required: true,
        min: 30,
        max: 300,
        unit: 'kg',
        helpText: 'مثال: ۶۸',
      },
      {
        id: 'bmi-waist',
        text: 'دور کمر (سانتی‌متر) — اختیاری',
        type: 'number',
        required: false,
        min: 50,
        max: 200,
        unit: 'cm',
        helpText: 'برای ارزیابی چربی abdominal',
      },
    ],
    scoreRanges: [
      { min: 0, max: 18.4, riskLevel: 'moderate', label: 'کمبود وزن', recommendation: 'با پزشک یا متخصص تغذیه مشورت کنید.' },
      { min: 18.5, max: 24.9, riskLevel: 'low', label: 'وزن نرمال', recommendation: 'وزن فعلی را حفظ کنید.' },
      { min: 25, max: 29.9, riskLevel: 'moderate', label: 'اضافه وزن', recommendation: 'رژیم متعادل و فعالیت بدنی منظم توصیه می‌شود.' },
      { min: 30, max: 34.9, riskLevel: 'high', label: 'چاقی درجه I', recommendation: 'مشورت با پزشک برای برنامه کاهش وزن.' },
      { min: 35, max: 100, riskLevel: 'high', label: 'چاقی درجه II و بالاتر', recommendation: 'ارجاع به متخصص تغذیه یا endocrinology توصیه می‌شود.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'screening-cardiovascular',
    slug: 'cardiovascular',
    category: 'cardiovascular',
    title: 'ارزیابی خطر قلبی-عروقی',
    description: 'پرسشنامه کوتاه بر اساس عوامل خطر شایع بیماری‌های قلبی.',
    estimatedMinutes: 5,
    isActive: true,
    targetAudience: 'بزرگسالان ۳۰ سال به بالا',
    disclaimer: 'این ارزیابی امتیاز خطر تقریبی است و جایگزین Framingham یا SCORE نیست.',
    questions: [
      {
        id: 'cv-age',
        text: 'سن شما',
        type: 'number',
        required: true,
        min: 18,
        max: 100,
        unit: 'سال',
      },
      {
        id: 'cv-gender',
        text: 'جنسیت',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'cv-g-m', label: 'مرد', value: 'male' },
          { id: 'cv-g-f', label: 'زن', value: 'female' },
        ],
      },
      {
        id: 'cv-smoking',
        text: 'آیا سیگار می‌کشید یا در ۱۲ ماه گذشته کشیده‌اید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'cv-diabetes',
        text: 'آیا دیابت دارید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'cv-hypertension',
        text: 'آیا فشار خون بالا دارید یا داروی فشار خون مصرف می‌کنید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'cv-family',
        text: 'آیا بستگان درجه یک شما سابقه بیماری قلبی زودرس (مرد < ۵۵، زن < ۶۵ سال) دارند؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'cv-cholesterol',
        text: 'آیا کلسترول بالا دارید یا داروی statin مصرف می‌کنید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'cv-activity',
        text: 'آیا حداقل ۱۵۰ دقیقه فعالیت بدنی متوسط در هفته دارید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'cv-chest-pain',
        text: 'آیا در ۳ ماه گذشته درد قفسه سینه با فعالیت داشته‌اید؟',
        type: 'boolean',
        required: true,
      },
    ],
    scoreRanges: [
      { min: 0, max: 2, riskLevel: 'low', label: 'خطر کم', recommendation: 'سبک زندگی سالم را حفظ کنید. چکاپ سالانه.' },
      { min: 3, max: 5, riskLevel: 'moderate', label: 'خطر متوسط', recommendation: 'کنترل فشار خون و لیpid. مشورت با پزشک.' },
      { min: 6, max: 9, riskLevel: 'high', label: 'خطر بالا', recommendation: 'ویزیت پزشک برای ارزیابی کامل. ECG و لیpid.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'screening-diabetes',
    slug: 'diabetes',
    category: 'diabetes',
    title: 'غربالگری دیابت (FINDRISC)',
    description: 'ارزیابی ۱۰ ساله خطر دیابت نوع ۲ بر اساس پرسشنامه FINDRISC.',
    estimatedMinutes: 4,
    isActive: true,
    targetAudience: 'بزرگسالان ۲۵ سال به بالا',
    questions: [
      {
        id: 'dm-age',
        text: 'سن',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'dm-age-1', label: 'زیر ۴۵ سال', value: 0 },
          { id: 'dm-age-2', label: '۴۵-۵۴ سال', value: 2 },
          { id: 'dm-age-3', label: '۵۵-۶۴ سال', value: 3 },
          { id: 'dm-age-4', label: 'بالای ۶۴ سال', value: 4 },
        ],
      },
      {
        id: 'dm-bmi',
        text: 'BMI',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'dm-bmi-1', label: 'کمتر از ۲۵', value: 0 },
          { id: 'dm-bmi-2', label: '۲۵-۳۰', value: 1 },
          { id: 'dm-bmi-3', label: 'بالای ۳۰', value: 3 },
        ],
      },
      {
        id: 'dm-waist',
        text: 'دور کمر',
        type: 'single_choice',
        required: true,
        helpText: 'مرد: بالای ۹۴ cm، زن: بالای ۸۰ cm',
        options: [
          { id: 'dm-waist-1', label: 'نرمال', value: 0 },
          { id: 'dm-waist-2', label: 'افزایش یافته', value: 3 },
        ],
      },
      {
        id: 'dm-activity',
        text: 'فعالیت بدنی کمتر از ۳۰ دقیقه در روز؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'dm-vegetables',
        text: 'آیا روزانه میوه یا سبزی می‌خورید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'dm-hypertension',
        text: 'آیا فشار خون بالا دارید یا دارو مصرف می‌کنید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'dm-glucose-history',
        text: 'آیا قبلاً قند خون بالا داشته‌اید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'dm-family',
        text: 'سابقه دیابت در خانواده درجه یک؟',
        type: 'boolean',
        required: true,
      },
    ],
    scoreRanges: [
      { min: 0, max: 6, riskLevel: 'low', label: 'خطر ۱٪', recommendation: 'سبک زندگی سالم. غربالگری هر ۳ سال.' },
      { min: 7, max: 11, riskLevel: 'moderate', label: 'خطر ۴٪', recommendation: 'آزمایش قند ناشتا. کاهش وزن.' },
      { min: 12, max: 14, riskLevel: 'moderate', label: 'خطر ۱۷٪', recommendation: 'آزمایش قند و HbA1c. مشورت تغذیه.' },
      { min: 15, max: 20, riskLevel: 'high', label: 'خطر ۳۳٪+', recommendation: 'ویزیت پزشک. آزمایش فوری.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'screening-mental-health',
    slug: 'mental-health',
    category: 'mental_health',
    title: 'غربالگری سلامت روان (PHQ-2 + GAD-2)',
    description: 'ارزیابی کوتاه علائم افسردگی و اضطراب در ۲ هفته گذشته.',
    estimatedMinutes: 3,
    isActive: true,
    targetAudience: 'بزرگسالان',
    disclaimer: 'در صورت افکار خودکشی، فوراً با ۱۴۸۰ یا ۱۱۵ تماس بگیرید.',
    questions: [
      {
        id: 'mh-interest',
        text: 'در ۲ هفته گذشته، چند روز علاقه یا لذت کمی از انجام کارها داشتید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'mh-i-0', label: 'اصلاً', value: 0 },
          { id: 'mh-i-1', label: 'چند روز', value: 1 },
          { id: 'mh-i-2', label: 'بیش از نیمی از روزها', value: 2 },
          { id: 'mh-i-3', label: 'تقریباً هر روز', value: 3 },
        ],
      },
      {
        id: 'mh-mood',
        text: 'در ۲ هفته گذشته، چند روز احساس افسردگی، ناامیدی یا بی‌ارزشی داشتید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'mh-m-0', label: 'اصلاً', value: 0 },
          { id: 'mh-m-1', label: 'چند روز', value: 1 },
          { id: 'mh-m-2', label: 'بیش از نیمی از روزها', value: 2 },
          { id: 'mh-m-3', label: 'تقریباً هر روز', value: 3 },
        ],
      },
      {
        id: 'mh-anxiety',
        text: 'در ۲ هفته گذشته، چند روز احساس بی‌قراری، اضطراب یا تنش داشتید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'mh-a-0', label: 'اصلاً', value: 0 },
          { id: 'mh-a-1', label: 'چند روز', value: 1 },
          { id: 'mh-a-2', label: 'بیش از نیمی از روزها', value: 2 },
          { id: 'mh-a-3', label: 'تقریباً هر روز', value: 3 },
        ],
      },
      {
        id: 'mh-worry',
        text: 'در ۲ هفته گذشته، چند روز نگرانی بیش از حد داشتید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'mh-w-0', label: 'اصلاً', value: 0 },
          { id: 'mh-w-1', label: 'چند روز', value: 1 },
          { id: 'mh-w-2', label: 'بیش از نیمی از روزها', value: 2 },
          { id: 'mh-w-3', label: 'تقریباً هر روز', value: 3 },
        ],
      },
      {
        id: 'mh-self-harm',
        text: 'آیا فکر می‌کنید که خودتان را آسیب بزنید یا بهتر است بمیرید؟',
        type: 'boolean',
        required: true,
      },
    ],
    scoreRanges: [
      { min: 0, max: 2, riskLevel: 'low', label: 'علائم minimal', recommendation: 'مراقبت خود را ادامه دهید.' },
      { min: 3, max: 5, riskLevel: 'moderate', label: 'علائم خفیف-متوسط', recommendation: 'مشورت با مشاور. PHQ-9 کامل.' },
      { min: 6, max: 12, riskLevel: 'high', label: 'علائم قابل توجه', recommendation: 'ویزیت روان‌پزشک یا روانشناس.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'screening-sleep',
    slug: 'sleep',
    category: 'sleep',
    title: 'ارزیابی کیفیت خواب',
    description: 'پرسشنامه کوتاه برای شناسایی اختلالات خواب شایع.',
    estimatedMinutes: 4,
    isActive: true,
    targetAudience: 'بزرگسالان',
    questions: [
      {
        id: 'sleep-duration',
        text: 'به طور متوسط چند ساعت در شب می‌خوابید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'sd-1', label: 'کمتر از ۵ ساعت', value: 3 },
          { id: 'sd-2', label: '۵-۶ ساعت', value: 2 },
          { id: 'sd-3', label: '۷-۸ ساعت', value: 0 },
          { id: 'sd-4', label: 'بیش از ۹ ساعت', value: 1 },
        ],
      },
      {
        id: 'sleep-latency',
        text: 'چقدر طول می‌کشد تا بخوابید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'sl-1', label: 'کمتر از ۱۵ دقیقه', value: 0 },
          { id: 'sl-2', label: '۱۵-۳۰ دقیقه', value: 1 },
          { id: 'sl-3', label: '۳۰-۶۰ دقیقه', value: 2 },
          { id: 'sl-4', label: 'بیش از ۱ ساعت', value: 3 },
        ],
      },
      {
        id: 'sleep-wake',
        text: 'آیا شب‌ها بیدار می‌شوید و دشوار به خواب برمی‌گردید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'sw-0', label: 'هرگز', value: 0 },
          { id: 'sw-1', label: 'گاهی', value: 1 },
          { id: 'sw-2', label: 'اغلب', value: 2 },
          { id: 'sw-3', label: 'همیشه', value: 3 },
        ],
      },
      {
        id: 'sleep-snore',
        text: 'آیا خرخر می‌کنید یا partner شما شکایت دارد؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'sleep-tired',
        text: 'آیا روزها احساس خستگی یا خواب‌آلودگی دارید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'st-0', label: 'هرگز', value: 0 },
          { id: 'st-1', label: 'گاهی', value: 1 },
          { id: 'st-2', label: 'اغلب', value: 2 },
          { id: 'st-3', label: 'همیشه', value: 3 },
        ],
      },
      {
        id: 'sleep-caffeine',
        text: 'آیا بعد از ساعت ۱۴ کافئین (قهوه، چای) مصرف می‌کنید؟',
        type: 'boolean',
        required: true,
      },
    ],
    scoreRanges: [
      { min: 0, max: 3, riskLevel: 'low', label: 'خواب مناسب', recommendation: 'عادات فعلی را حفظ کنید.' },
      { min: 4, max: 7, riskLevel: 'moderate', label: 'کیفیت خواب متوسط', recommendation: 'بهداشت خواب: زمان ثابت، بدون صفحه قبل خواب.' },
      { min: 8, max: 15, riskLevel: 'high', label: 'اختلال احتمالی خواب', recommendation: 'مشورت با پزشک. غربالگری apnea.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'screening-nutrition',
    slug: 'nutrition',
    category: 'nutrition',
    title: 'ارزیابی عادات تغذیه‌ای',
    description: 'بررسی الگوی غذایی روزانه و شناسایی نقاط بهبود.',
    estimatedMinutes: 5,
    isActive: true,
    targetAudience: 'همه',
    questions: [
      {
        id: 'nut-fruits',
        text: 'چند وعده میوه در روز مصرف می‌کنید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'nf-0', label: '۰', value: 3 },
          { id: 'nf-1', label: '۱', value: 2 },
          { id: 'nf-2', label: '۲', value: 1 },
          { id: 'nf-3', label: '۳ یا بیشتر', value: 0 },
        ],
      },
      {
        id: 'nut-vegetables',
        text: 'چند وعده سبزیجات در روز؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'nv-0', label: '۰-۱', value: 3 },
          { id: 'nv-1', label: '۲', value: 1 },
          { id: 'nv-2', label: '۳ یا بیشتر', value: 0 },
        ],
      },
      {
        id: 'nut-water',
        text: 'چند لیوان آب در روز می‌نوشید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'nw-1', label: 'کمتر از ۴', value: 2 },
          { id: 'nw-2', label: '۴-۶', value: 1 },
          { id: 'nw-3', label: '۷ یا بیشتر', value: 0 },
        ],
      },
      {
        id: 'nut-fastfood',
        text: 'چند بار در هفته fast food یا غذای آماده می‌خورید؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'nff-0', label: 'هرگز', value: 0 },
          { id: 'nff-1', label: '۱-۲ بار', value: 1 },
          { id: 'nff-2', label: '۳-۴ بار', value: 2 },
          { id: 'nff-3', label: '۵ بار یا بیشتر', value: 3 },
        ],
      },
      {
        id: 'nut-salt',
        text: 'آیا غذای اضافه نمک می‌زنید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'nut-sugar',
        text: 'آیا روزانه نوشابه یا شیرینی مصرف می‌کنید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'nut-breakfast',
        text: 'آیا صبحانه می‌خورید؟',
        type: 'boolean',
        required: true,
      },
    ],
    scoreRanges: [
      { min: 0, max: 3, riskLevel: 'low', label: 'تغذیه خوب', recommendation: 'ادامه دهید.' },
      { min: 4, max: 7, riskLevel: 'moderate', label: 'نیاز به بهبود', recommendation: 'افزایش میوه/سبزی، کاهش نمک و قند.' },
      { min: 8, max: 12, riskLevel: 'high', label: 'عادات ناسالم', recommendation: 'مشورت با متخصص تغذیه.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'screening-activity',
    slug: 'activity',
    category: 'activity',
    title: 'ارزیابی فعالیت بدنی',
    description: 'بر اساس توصیه‌های WHO برای بزرگسالان.',
    estimatedMinutes: 3,
    isActive: true,
    targetAudience: 'بزرگسالان ۱۸-۶۴ سال',
    questions: [
      {
        id: 'act-moderate',
        text: 'چند روز در هفته حداقل ۳۰ دقیقه فعالیت متوسط (پیاده‌روی تند) دارید؟',
        type: 'number',
        required: true,
        min: 0,
        max: 7,
        unit: 'روز',
      },
      {
        id: 'act-vigorous',
        text: 'چند روز در هفته فعالیت شدید (دویدن، ورزش پرش) دارید؟',
        type: 'number',
        required: true,
        min: 0,
        max: 7,
        unit: 'روز',
      },
      {
        id: 'act-sitting',
        text: 'چند ساعت در روز می‌نشینید (کار، TV)؟',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'as-1', label: 'کمتر از ۴', value: 0 },
          { id: 'as-2', label: '۴-۶', value: 1 },
          { id: 'as-3', label: '۶-۸', value: 2 },
          { id: 'as-4', label: 'بیش از ۸', value: 3 },
        ],
      },
      {
        id: 'act-stairs',
        text: 'آیا ترجیح می‌دهید از پله بالا بروید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'act-limitation',
        text: 'آیا درد یا محدودیت جسمی مانع فعالیت شماست؟',
        type: 'boolean',
        required: true,
      },
    ],
    scoreRanges: [
      { min: 0, max: 2, riskLevel: 'low', label: 'فعال', recommendation: 'حداقل ۱۵۰ دقیقه/هفته — عالی!' },
      { min: 3, max: 5, riskLevel: 'moderate', label: 'نیمه‌فعال', recommendation: 'افزایش تدریجی به ۱۵۰ دقیقه.' },
      { min: 6, max: 10, riskLevel: 'high', label: ' کم‌تحرک', recommendation: 'شروع با ۱۰ دقیقه پیاده‌روی روزانه.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
  {
    id: 'screening-gestational-diabetes',
    slug: 'gestational-diabetes',
    category: 'gestational_diabetes',
    title: 'غربالگری دیابت بارداری',
    description: 'برای زنان باردار — ارزیابی خطر GDM.',
    estimatedMinutes: 4,
    isActive: true,
    targetAudience: 'زنان باردار',
    disclaimer: 'OGTT در هفته ۲۴-۲۸ بارداری استاندارد طلایی است.',
    questions: [
      {
        id: 'gdm-pregnant',
        text: 'آیا در حال حاضر باردار هستید؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'gdm-week',
        text: 'هفته بارداری',
        type: 'number',
        required: true,
        min: 1,
        max: 42,
        unit: 'هفته',
        dependsOn: { questionId: 'gdm-pregnant', value: true },
      },
      {
        id: 'gdm-age',
        text: 'سن',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'gdm-age-1', label: 'زیر ۲۵', value: 0 },
          { id: 'gdm-age-2', label: '۲۵-۳۴', value: 1 },
          { id: 'gdm-age-3', label: '۳۵ و بالاتر', value: 3 },
        ],
      },
      {
        id: 'gdm-bmi-start',
        text: 'BMI در شروع بارداری',
        type: 'single_choice',
        required: true,
        options: [
          { id: 'gdm-bmi-1', label: 'کمتر از ۲۵', value: 0 },
          { id: 'gdm-bmi-2', label: '۲۵-۳۰', value: 1 },
          { id: 'gdm-bmi-3', label: 'بالای ۳۰', value: 2 },
        ],
      },
      {
        id: 'gdm-family',
        text: 'سابقه دیابت در خانواده؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'gdm-previous-gdm',
        text: 'دیابت بارداری در بارداری قبلی؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'gdm-pcos',
        text: 'سندرم تخمدان پلی‌کیستic (PCOS)؟',
        type: 'boolean',
        required: true,
      },
      {
        id: 'gdm-glucose-test',
        text: 'آیا تست OGTT انجام داده‌اید؟',
        type: 'boolean',
        required: true,
      },
    ],
    scoreRanges: [
      { min: 0, max: 2, riskLevel: 'low', label: 'خطر پایین', recommendation: 'OGTT در هفته ۲۴-۲۸.' },
      { min: 3, max: 5, riskLevel: 'moderate', label: 'خطر متوسط', recommendation: 'OGTT زودتر (۱۶-۱۸ هفته) + تکرار ۲۴-۲۸.' },
      { min: 6, max: 10, riskLevel: 'high', label: 'خطر بالا', recommendation: 'مشورت فوری با متخصص زنان. پایش قند.' },
    ],
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2025-06-01T00:00:00.000Z',
  },
];

// ─── Demo Screening Results ─────────────────────────────────────────────────────

export const screeningResults: ScreeningResult[] = [
  {
    id: 'sr-sara-bmi-1',
    patientId: 'p-citizen-1',
    screeningId: 'screening-bmi',
    screeningTitle: 'محاسبه BMI و ارزیابی وزن',
    answers: [
      { questionId: 'bmi-height', value: 165 },
      { questionId: 'bmi-weight', value: 68 },
      { questionId: 'bmi-waist', value: 78 },
    ],
    score: 25.0,
    riskLevel: 'moderate',
    summary: 'BMI شما ۲۵.۰ است — در محدوده اضافه وزن.',
    recommendations: [
      'هدف: BMI ۲۳-۲۴ با کاهش تدریجی ۰.۵ kg در هفته',
      'پیاده‌روی ۳۰ دقیقه، ۵ روز در هفته',
      'مشورت با متخصص تغذیه برای کنترل LDL',
    ],
    completedAt: '2025-07-10T07:35:00.000Z',
    sourceType: 'user_entered',
    verificationStatus: 'self_reported',
    createdAt: '2025-07-10T07:35:00.000Z',
    updatedAt: '2025-07-10T07:35:00.000Z',
  },
  {
    id: 'sr-sara-cv-1',
    patientId: 'p-citizen-1',
    screeningId: 'screening-cardiovascular',
    screeningTitle: 'ارزیابی خطر قلبی-عروقی',
    answers: [
      { questionId: 'cv-age', value: 34 },
      { questionId: 'cv-gender', value: 'female' },
      { questionId: 'cv-smoking', value: false },
      { questionId: 'cv-diabetes', value: false },
      { questionId: 'cv-hypertension', value: true },
      { questionId: 'cv-family', value: false },
      { questionId: 'cv-cholesterol', value: true },
      { questionId: 'cv-activity', value: true },
      { questionId: 'cv-chest-pain', value: false },
    ],
    score: 4,
    riskLevel: 'moderate',
    summary: 'با توجه به فشار خون و LDL بالا، خطر متوسط دارید.',
    recommendations: [
      'ادامه لوزارتان طبق دستور پزشک',
      'رژیم DASH و کاهش LDL',
      'ECG سالانه',
    ],
    completedAt: '2025-06-01T10:00:00.000Z',
    sourceType: 'user_entered',
    verificationStatus: 'pending_review',
    createdAt: '2025-06-01T10:00:00.000Z',
    updatedAt: '2025-06-01T10:00:00.000Z',
  },
  {
    id: 'sr-mother-dm-1',
    patientId: 'p-mother-1',
    screeningId: 'screening-diabetes',
    screeningTitle: 'غربالگری دیابت (FINDRISC)',
    answers: [
      { questionId: 'dm-age', value: 4 },
      { questionId: 'dm-bmi', value: 1 },
      { questionId: 'dm-waist', value: 3 },
      { questionId: 'dm-activity', value: true },
      { questionId: 'dm-vegetables', value: true },
      { questionId: 'dm-hypertension', value: true },
      { questionId: 'dm-glucose-history', value: true },
      { questionId: 'dm-family', value: true },
    ],
    score: 14,
    riskLevel: 'high',
    summary: 'خطر بالای دیابت — بیمار شناخته‌شده دیابت نوع ۲.',
    recommendations: [
      'HbA1c هر ۳-۶ ماه',
      'پایش قند خانگی',
      'ویزیت منظم endocrinology',
    ],
    completedAt: '2025-05-01T09:00:00.000Z',
    sourceType: 'care_team',
    verificationStatus: 'verified',
    createdAt: '2025-05-01T09:00:00.000Z',
    updatedAt: '2025-05-01T09:00:00.000Z',
  },
  {
    id: 'sr-sara-sleep-1',
    patientId: 'p-citizen-1',
    screeningId: 'screening-sleep',
    screeningTitle: 'ارزیابی کیفیت خواب',
    answers: [
      { questionId: 'sleep-duration', value: 0 },
      { questionId: 'sleep-latency', value: 1 },
      { questionId: 'sleep-wake', value: 1 },
      { questionId: 'sleep-snore', value: false },
      { questionId: 'sleep-tired', value: 1 },
      { questionId: 'sleep-caffeine', value: false },
    ],
    score: 3,
    riskLevel: 'low',
    summary: 'کیفیت خواب شما در محدوده مناسب است.',
    recommendations: ['حفظ زمان ثابت خواب', 'اتاق تاریک و خنک'],
    completedAt: '2025-05-15T21:00:00.000Z',
    sourceType: 'user_entered',
    verificationStatus: 'self_reported',
    createdAt: '2025-05-15T21:00:00.000Z',
    updatedAt: '2025-05-15T21:00:00.000Z',
  },
];

export const screeningBySlug = (slug: string): Screening | undefined =>
  screenings.find((s) => s.slug === slug);

export const screeningResultsByPatient = (patientId: string): ScreeningResult[] =>
  screeningResults.filter((r) => r.patientId === patientId);

/** Calculate BMI from height (cm) and weight (kg). */
export function calculateBMI(heightCm: number, weightKg: number): number {
  const heightM = heightCm / 100;
  return Math.round((weightKg / (heightM * heightM)) * 10) / 10;
}

/** Get risk level label for a BMI score using screening-bmi ranges. */
export function getBMIRiskLevel(bmi: number): Screening['scoreRanges'] extends (infer R)[] ? R : never {
  const bmiScreening = screenings.find((s) => s.slug === 'bmi');
  const range = bmiScreening?.scoreRanges?.find((r) => bmi >= r.min && bmi <= r.max);
  return range as Screening['scoreRanges'] extends (infer R)[] ? R : never;
}
